/**
 * 開發用的假行程。設定 MOCK_PLAN=1 就會走這條路，不會呼叫模型、不花錢。
 * 用途是驗證串流、渲染、刪減與費用重算 —— 內容全是虛構的，店名都標了（示範）。
 */
export const MOCK_TRIP_JSON = JSON.stringify({
  title: "台北義式一日：中山線散步（示範）",
  summary:
    "從台中高鐵站北上，中午在中山站附近吃義式，下午在赤峰街一帶走走拍照，傍晚回程。整段以捷運加步行為主，走路距離都在十分鐘內。",
  stops: [
    {
      kind: "transit",
      verified: "landmark",
      name: "高鐵 台中→台北",
      time: "09:00",
      duration: "約 60 分鐘",
      howTo: "台中高鐵站搭北上列車至台北站，出站後跟著指標轉乘捷運淡水信義線。",
      cost: 700,
      costUnit: "每人",
      notes: ["可開電子發票"],
    },
    {
      kind: "transit",
      verified: "landmark",
      name: "捷運 台北車站→中山站",
      time: "10:15",
      duration: "約 4 分鐘",
      howTo: "搭淡水信義線往淡水方向，一站到中山，走 4 號出口，步行 3 分鐘。",
      cost: 20,
      costUnit: "每人",
    },
    {
      kind: "food",
      name: "中山站周邊義式餐酒館（示範）",
      area: "中山區",
      verified: "generic",
      time: "11:30",
      duration: "約 90 分鐘",
      howTo: "中山站 4 號出口出站後直行，第二個路口右轉。",
      detail: "手工麵與窯烤披薩為主，兩人分食一份前菜加兩份主餐剛好。",
      hours: "11:30–14:30、17:30–21:00（週二公休）",
      cost: 750,
      costUnit: "每人",
      rainPlan: "店內全室內座位，從捷運站出口有騎樓可走。",
      notes: ["可指定不辣", "可開統編發票", "需低消一份主餐"],
      booking: "假日建議提前三天訂位",
    },
    {
      kind: "sight",
      name: "赤峰街巷弄（示範景點）",
      area: "大同區",
      verified: "landmark",
      time: "13:30",
      duration: "約 90 分鐘",
      howTo: "餐廳步行 6 分鐘即到。",
      detail: "老公寓改成的選物店與咖啡店密集，紅磚牆與鐵窗花是常見的拍照背景。",
      hours: "多數店家 12:00 起營業",
      cost: 0,
      costUnit: "每人",
      rainPlan: "改到中山地下書街，從 R 出口整段有遮蔽。",
      notes: ["室內外皆有", "多數店家可刷卡"],
    },
    {
      kind: "sight",
      name: "市立美術館（示範）",
      area: "中山區",
      verified: "unverified",
      time: "15:30",
      duration: "約 120 分鐘",
      howTo: "中山站搭淡水信義線至圓山站 1 號出口，步行 10 分鐘。",
      detail: "常設展與特展分開售票，室內空間大，適合下午避開人潮。",
      hours: "09:30–17:30（週一休館）",
      cost: 30,
      costUnit: "每人",
      rainPlan: "本身就是室內行程，雨天首選。",
      notes: ["學生票半價", "可開發票"],
    },
    {
      kind: "transit",
      verified: "landmark",
      name: "捷運＋高鐵 回台中",
      time: "18:00",
      duration: "約 90 分鐘",
      howTo: "圓山站搭淡水信義線至台北車站，轉高鐵南下。",
      cost: 720,
      costUnit: "每人",
      notes: ["離峰班次較便宜"],
    },
  ],
  extras: [
    { name: "寧夏夜市（示範）", kind: "food", why: "若想把晚餐留在台北，走路從中山站約 12 分鐘。", cost: 250, costUnit: "每人", area: "大同區" },
    { name: "迪化街老屋咖啡（示範）", kind: "sight", why: "人比赤峰街少，二樓窗邊採光好。", cost: 180, costUnit: "每人", area: "大同區" },
    { name: "中山站商旅（示範）", kind: "stay", why: "早鳥價含雙人早餐，走路到捷運站 5 分鐘。", cost: 2600, costUnit: "每晚", area: "中山區" },
  ],
  tips: [
    "這是模擬資料（MOCK_PLAN=1），店名與價格都是虛構的。",
    "捷運出口編號與步行時間，出發前用地圖再確認一次比較保險。",
    "想壓低花費，先把票價最高的那一站移除，下面金額會立刻重算。",
  ],
});
